/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export interface InstantiateMsg {
  admins: Addr[];
}
export type ExecuteMsg = {
  start_bidding: {
    config: BiddingPeriod;
  };
} | {
  end_bidding: {
    accepted_bids: Addr[];
    withdrawal_address?: Addr | null;
  };
} | {
  bid: {
    address?: Addr | null;
  };
};
export type Timestamp = Uint64;
export type Uint64 = string;
export type Uint128 = string;
export interface BiddingPeriod {
  accepted_bidders: number;
  denom: string;
  description?: string | null;
  expires_at: Timestamp;
  minimum_bid: Uint128;
  name: string;
}
export type QueryMsg = {
  bidding_period: {};
} | {
  bids: {};
} | {
  bid: {
    address: Addr;
  };
};
export interface BidResponse {
  bid?: Bid | null;
}
export interface Bid {
  amount: Uint128;
  bidder: Addr;
}
export interface BiddingPeriodResponse {
  bidding_period?: BiddingPeriod | null;
}
export interface BidsResponse {
  bids: Bid[];
}